[package]
name = "tracky-core"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.45", features = ["serde"] }
rusqlite = { version = "0.40.2", features = ["bundled"] }
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.21"
url = "2.5.8"
uuid = { version = "1.26.1", features = ["v4", "serde"] }
